"""Add claim review and approval fields

Revision ID: 26099498db06
Revises: 84c616989a45
Create Date: 2025-12-02 12:52:28.016091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26099498db06'
down_revision = '84c616989a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fraud_check_performed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fraud_check_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fraud_check_result', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fraud_risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approval_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_claim_reviewed_by', 'insurer', ['reviewed_by'], ['id'])
        batch_op.create_foreign_key('fk_claim_approved_by', 'insurer', ['approved_by'], ['id'])
    
    # Set default value for existing records
    op.execute("UPDATE claim SET fraud_check_performed = 0 WHERE fraud_check_performed IS NULL")
    
    # Now make it non-nullable
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('fraud_check_performed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_constraint('fk_claim_approved_by', type_='foreignkey')
        batch_op.drop_constraint('fk_claim_reviewed_by', type_='foreignkey')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approval_date')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('fraud_risk_score')
        batch_op.drop_column('fraud_check_result')
        batch_op.drop_column('fraud_check_date')
        batch_op.drop_column('fraud_check_performed')
        batch_op.drop_column('review_notes')
        batch_op.drop_column('review_date')
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###
