"""Add policy status and cancellation fields

Revision ID: 84c616989a45
Revises: 
Create Date: 2025-12-02 12:31:02.095785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c616989a45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_policy_cancelled_by', 'insurer', ['cancelled_by'], ['id'])
    
    # Set default value for existing records
    op.execute("UPDATE policy SET status = 'Active' WHERE status IS NULL")
    
    # Now make it non-nullable
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.drop_constraint('fk_policy_cancelled_by', type_='foreignkey')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancellation_date')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
